/-
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Formal Frontier Agents
-/
module

public import Mathlib.Analysis.Normed.Field.Krasner
public import Mathlib.Analysis.Normed.Field.Approximation
public import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic

/-!
# Monic polynomial root-field stability

The reference polynomial is monic and separable, and both it and the
same-`natDegree` comparison polynomial split in a fixed normed extension
carrying `IsKrasner K L`. A sufficiently small uniform coefficientwise
perturbation makes the comparison separable and preserves the intermediate
field generated by all its roots. One-sided Krasner inclusion and positive
separation/quantitative bounds are also available with their weaker respective
assumptions; in particular the finite separation lemmas do not need the
`IsKrasner` instance. Reverse inclusion uses an asymmetric estimate with two
copies of the selected root's error and one copy at another root. Empty root
sets (including monic constants) are handled explicitly.

The ambient normed extension and splitting assumptions are not produced by
this module; the result concerns root-generated intermediate fields, not a
canonical splitting-field object.
-/

public section

set_option warningAsError true

open Polynomial

noncomputable section

namespace IsKrasner

variable {K L : Type*} [Field K] [NormedField L] [Algebra K L] [IsKrasner K L]

/-!
These lemmas prove local constancy of the root-generated field for monic
separable polynomials splitting in one Krasner normed extension. They isolate
the finite-root estimates, nearby separability and forward and reverse Krasner
arguments for downstream use.
-/

/-- A set of separable elements lies in the field generated by a second set if
each element satisfies Krasner's strict conjugate-distance condition with an
integral element of the second set. -/
theorem adjoin_le_adjoin_of_forall_exists_close
    {S T : Set L}
    (h : ∀ x ∈ S,
      IsSeparable K x ∧
      ((minpoly K x).map (algebraMap K L)).Splits ∧
      ∃ y ∈ T, IsIntegral K y ∧
        ∀ x' : L, IsConjRoot K x x' → x ≠ x' → ‖x - y‖ < ‖x - x'‖) :
    IntermediateField.adjoin K S ≤ IntermediateField.adjoin K T := by
  rw [IntermediateField.adjoin_le_iff]
  intro x hx
  obtain ⟨hxsep, hxsplit, y, hyT, hyint, hxy⟩ := h x hx
  have hxKy : x ∈ IntermediateField.adjoin K ({y} : Set L) :=
    IsKrasner.krasner hxsep hxsplit hyint hxy
  exact (IntermediateField.adjoin.mono K {y} T
    (Set.singleton_subset_iff.mpr hyT)) hxKy

/-- Polynomial-root specialization of
`IsKrasner.adjoin_le_adjoin_of_forall_exists_close`. The reference polynomial
is separable and splits in the ambient extension; the comparison polynomial
need not yet be separable, but its selected roots are automatically integral
over the base field. -/
theorem adjoin_rootSet_le_adjoin_rootSet_of_forall_exists_close
    {f g : K[X]}
    (hfsep : f.Separable)
    (hfsplit : (f.map (algebraMap K L)).Splits)
    (hclose : ∀ x ∈ f.rootSet L, ∃ y ∈ g.rootSet L,
      ∀ x' : L, IsConjRoot K x x' → x ≠ x' → ‖x - y‖ < ‖x - x'‖) :
    IntermediateField.adjoin K (f.rootSet L) ≤
      IntermediateField.adjoin K (g.rootSet L) := by
  apply adjoin_le_adjoin_of_forall_exists_close
  intro x hx
  have hminpoly_dvd : minpoly K x ∣ f := minpoly.dvd K x (mem_rootSet.mp hx).2
  refine ⟨hfsep.of_dvd hminpoly_dvd, ?_, ?_⟩
  · exact hfsplit.of_dvd (map_ne_zero hfsep.ne_zero)
      (Polynomial.map_dvd (algebraMap K L) hminpoly_dvd)
  · obtain ⟨y, hy, hxy⟩ := hclose x hx
    exact ⟨y, hy, (isAlgebraic_of_mem_rootSet hy).isIntegral, hxy⟩

omit [IsKrasner K L] in
/-- The nonzero conjugate distances of the roots of a polynomial have a
uniform positive lower bound. This is the finite-root input needed to turn a
pointwise Krasner condition into one coefficient neighbourhood. -/
theorem exists_pos_le_norm_sub_of_isConjRoot
    (f : K[X]) :
    ∃ δ : ℝ, 0 < δ ∧
      ∀ x ∈ f.rootSet L, ∀ x' : L,
        IsConjRoot K x x' → x ≠ x' → δ ≤ ‖x - x'‖ := by
  classical
  let roots : Finset L := Set.Finite.toFinset (f.rootSet_finite L)
  let conjugates (x : L) : Finset L :=
    Set.Finite.toFinset ((minpoly K x).rootSet_finite L)
  let distances : Finset ℝ := roots.biUnion fun x ↦
    ((conjugates x).filter fun x' ↦ x ≠ x').image fun x' ↦ ‖x - x'‖
  have mem_distances {x x' : L} (hx : x ∈ f.rootSet L)
      (hx' : IsConjRoot K x x') (hne : x ≠ x') : ‖x - x'‖ ∈ distances := by
    simp only [distances, Finset.mem_biUnion, Finset.mem_image, Finset.mem_filter]
    refine ⟨x, ?_, x', ⟨?_, hne⟩, rfl⟩
    · exact (f.rootSet_finite L).mem_toFinset.mpr hx
    · apply ((minpoly K x).rootSet_finite L).mem_toFinset.mpr
      rwa [← isConjRoot_iff_mem_minpoly_rootSet
        (isAlgebraic_of_mem_rootSet hx).isIntegral]
  have distances_pos {r : ℝ} (hr : r ∈ distances) : 0 < r := by
    simp only [distances, Finset.mem_biUnion, Finset.mem_image,
      Finset.mem_filter] at hr
    obtain ⟨x, _, x', ⟨_, hne⟩, rfl⟩ := hr
    exact norm_pos_iff.mpr (sub_ne_zero.mpr hne)
  by_cases hdistances : distances.Nonempty
  · refine ⟨distances.min' hdistances, ?_, ?_⟩
    · exact distances_pos (distances.min'_mem hdistances)
    · intro x hx x' hx' hne
      exact distances.min'_le _ (mem_distances hx hx' hne)
  · refine ⟨1, zero_lt_one, ?_⟩
    intro x hx x' hx' hne
    exfalso
    apply hdistances
    exact ⟨‖x - x'‖, mem_distances hx hx' hne⟩

omit [IsKrasner K L] in
/-- The distances between distinct roots of a polynomial have a uniform
positive lower bound. Unlike
`IsKrasner.exists_pos_le_norm_sub_of_isConjRoot`, this also separates roots
belonging to different irreducible factors. -/
theorem exists_pos_le_norm_sub_of_distinct_roots
    (f : K[X]) :
    ∃ δ : ℝ, 0 < δ ∧
      ∀ x ∈ f.rootSet L, ∀ x' ∈ f.rootSet L,
        x ≠ x' → δ ≤ ‖x - x'‖ := by
  classical
  let roots : Finset L := Set.Finite.toFinset (f.rootSet_finite L)
  let distances : Finset ℝ := roots.biUnion fun x ↦
    (roots.filter fun x' ↦ x ≠ x').image fun x' ↦ ‖x - x'‖
  have mem_distances {x x' : L} (hx : x ∈ f.rootSet L)
      (hx' : x' ∈ f.rootSet L) (hne : x ≠ x') : ‖x - x'‖ ∈ distances := by
    simp only [distances, Finset.mem_biUnion, Finset.mem_image, Finset.mem_filter]
    refine ⟨x, ?_, x', ⟨?_, hne⟩, rfl⟩
    · exact (f.rootSet_finite L).mem_toFinset.mpr hx
    · exact (f.rootSet_finite L).mem_toFinset.mpr hx'
  have distances_pos {r : ℝ} (hr : r ∈ distances) : 0 < r := by
    simp only [distances, Finset.mem_biUnion, Finset.mem_image,
      Finset.mem_filter] at hr
    obtain ⟨x, _, x', ⟨_, hne⟩, rfl⟩ := hr
    exact norm_pos_iff.mpr (sub_ne_zero.mpr hne)
  by_cases hdistances : distances.Nonempty
  · refine ⟨distances.min' hdistances, ?_, ?_⟩
    · exact distances_pos (distances.min'_mem hdistances)
    · intro x hx x' hx' hne
      exact distances.min'_le _ (mem_distances hx hx' hne)
  · refine ⟨1, zero_lt_one, ?_⟩
    intro x hx x' hx' hne
    exfalso
    apply hdistances
    exact ⟨‖x - x'‖, mem_distances hx hx' hne⟩

section Quantitative

variable {K₀ L₀ : Type*} [NormedField K₀] [NormedField L₀]
  [NormedAlgebra K₀ L₀] [IsKrasner K₀ L₀]

omit [IsKrasner K₀ L₀] in
/-- A monic polynomial admits one positive coefficient radius for which the
quantitative root-continuity estimate is smaller than every nontrivial
conjugate distance of every root. The radius is uniform because the reference
root set is finite. The constant-polynomial case is handled vacuously; in the
nonempty-root case, monicity supplies the positive degree needed to invert the
real exponent. -/
theorem exists_pos_root_continuity_bound_lt_of_monic
    (f : K₀[X]) (hfm : f.Monic) :
    ∃ ε : ℝ, 0 < ε ∧
      ∀ x ∈ f.rootSet L₀, ∀ x' : L₀,
        IsConjRoot K₀ x x' → x ≠ x' →
          ((f.natDegree + 1) * ε) ^ (f.natDegree : ℝ)⁻¹ * max ‖x‖ 1 <
            ‖x - x'‖ := by
  classical
  obtain ⟨δ, hδ, hδ_le⟩ := exists_pos_le_norm_sub_of_isConjRoot (L := L₀) f
  by_cases hroots : (f.rootSet L₀).Nonempty
  · let roots : Finset L₀ := Set.Finite.toFinset (f.rootSet_finite L₀)
    let M : ℝ := ∑ x ∈ roots, max ‖x‖ 1
    have mem_roots {x : L₀} (hx : x ∈ f.rootSet L₀) : x ∈ roots :=
      (f.rootSet_finite L₀).mem_toFinset.mpr hx
    have term_le_M {x : L₀} (hx : x ∈ roots) : max ‖x‖ 1 ≤ M := by
      apply Finset.single_le_sum (s := roots) (f := fun y : L₀ ↦ max ‖y‖ 1)
      · intro y hy
        positivity
      · exact hx
    obtain ⟨x₀, hx₀⟩ := hroots
    have hM : 0 < M := zero_lt_one.trans_le
      ((le_max_right ‖x₀‖ 1).trans (term_le_M (mem_roots hx₀)))
    have hdeg : f.natDegree ≠ 0 := by
      intro hdeg
      have hf : f = 1 := hfm.natDegree_eq_zero.mp hdeg
      simp [hf] at hx₀
    let r : ℝ := δ / (2 * M)
    have hr : 0 < r := by
      dsimp [r]
      positivity
    let ε : ℝ := r ^ f.natDegree / (f.natDegree + 1)
    have hε : 0 < ε := by
      dsimp [ε]
      positivity
    refine ⟨ε, hε, ?_⟩
    intro x hx x' hx' hne
    have hbase : ((f.natDegree : ℝ) + 1) * ε = r ^ f.natDegree := by
      dsimp [ε]
      field_simp
    calc
      ((f.natDegree + 1) * ε) ^ (f.natDegree : ℝ)⁻¹ * max ‖x‖ 1 =
          r * max ‖x‖ 1 := by
            rw [hbase, Real.pow_rpow_inv_natCast hr.le hdeg]
      _ ≤ r * M := mul_le_mul_of_nonneg_left (term_le_M (mem_roots hx)) hr.le
      _ = δ / 2 := by
        dsimp [r]
        field_simp
      _ < δ := by linarith
      _ ≤ ‖x - x'‖ := hδ_le x hx x' hx' hne
  · refine ⟨1, zero_lt_one, ?_⟩
    intro x hx
    exact (hroots ⟨x, hx⟩).elim

omit [IsKrasner K₀ L₀] in
/-- A monic polynomial admits one positive coefficient radius for which twice
the root-continuity estimate at one reference root plus the estimate at any
second root is smaller than the distance between them. The asymmetric extra
copy is what is needed both for injectivity and for the reverse Krasner
argument. -/
theorem exists_pos_two_add_root_continuity_bounds_lt_of_monic
    (f : K₀[X]) (hfm : f.Monic) :
    ∃ ε : ℝ, 0 < ε ∧
      ∀ x ∈ f.rootSet L₀, ∀ x' ∈ f.rootSet L₀, x ≠ x' →
        2 * (((f.natDegree + 1) * ε) ^ (f.natDegree : ℝ)⁻¹ * max ‖x‖ 1) +
          ((f.natDegree + 1) * ε) ^ (f.natDegree : ℝ)⁻¹ * max ‖x'‖ 1 <
            ‖x - x'‖ := by
  classical
  obtain ⟨δ, hδ, hδ_le⟩ := exists_pos_le_norm_sub_of_distinct_roots (L := L₀) f
  by_cases hroots : (f.rootSet L₀).Nonempty
  · let roots : Finset L₀ := Set.Finite.toFinset (f.rootSet_finite L₀)
    let M : ℝ := ∑ x ∈ roots, max ‖x‖ 1
    have mem_roots {x : L₀} (hx : x ∈ f.rootSet L₀) : x ∈ roots :=
      (f.rootSet_finite L₀).mem_toFinset.mpr hx
    have term_le_M {x : L₀} (hx : x ∈ roots) : max ‖x‖ 1 ≤ M := by
      apply Finset.single_le_sum (s := roots) (f := fun y : L₀ ↦ max ‖y‖ 1)
      · intro y hy
        positivity
      · exact hx
    obtain ⟨x₀, hx₀⟩ := hroots
    have hM : 0 < M := zero_lt_one.trans_le
      ((le_max_right ‖x₀‖ 1).trans (term_le_M (mem_roots hx₀)))
    have hdeg : f.natDegree ≠ 0 := by
      intro hdeg
      have hf : f = 1 := hfm.natDegree_eq_zero.mp hdeg
      simp [hf] at hx₀
    let r : ℝ := δ / (8 * M)
    have hr : 0 < r := by
      dsimp [r]
      positivity
    let ε : ℝ := r ^ f.natDegree / (f.natDegree + 1)
    have hε : 0 < ε := by
      dsimp [ε]
      positivity
    refine ⟨ε, hε, ?_⟩
    intro x hx x' hx' hne
    have hbase : ((f.natDegree : ℝ) + 1) * ε = r ^ f.natDegree := by
      dsimp [ε]
      field_simp
    calc
      2 * (((f.natDegree + 1) * ε) ^ (f.natDegree : ℝ)⁻¹ * max ‖x‖ 1) +
          ((f.natDegree + 1) * ε) ^ (f.natDegree : ℝ)⁻¹ * max ‖x'‖ 1 =
          2 * (r * max ‖x‖ 1) + r * max ‖x'‖ 1 := by
            rw [hbase, Real.pow_rpow_inv_natCast hr.le hdeg]
      _ ≤ 2 * (r * M) + r * M := by
        exact add_le_add
          (mul_le_mul_of_nonneg_left
            (mul_le_mul_of_nonneg_left (term_le_M (mem_roots hx)) hr.le) zero_le_two)
          (mul_le_mul_of_nonneg_left (term_le_M (mem_roots hx')) hr.le)
      _ = 3 * δ / 8 := by
        dsimp [r]
        field_simp
        norm_num
      _ < δ := by linarith
      _ ≤ ‖x - x'‖ := hδ_le x hx x' hx' hne
  · refine ⟨1, zero_lt_one, ?_⟩
    intro x hx
    exact (hroots ⟨x, hx⟩).elim

omit [IsKrasner K₀ L₀] in
/-- A sufficiently small coefficient perturbation of a monic separable
polynomial remains separable. The quantitative hypothesis makes the root
selected near each reference root injective; equality of the degrees then
forces the comparison polynomial to have the maximal number of distinct
roots. -/
theorem separable_of_norm_coeff_sub_lt
    {f g : K₀[X]} {ε : ℝ}
    (hε : 0 < ε)
    (hfm : f.Monic)
    (hgm : g.Monic)
    (hfsep : f.Separable)
    (hdeg : g.natDegree = f.natDegree)
    (hcoeff : ∀ i : ℕ, ‖g.coeff i - f.coeff i‖ < ε)
    (hfsplit : (f.map (algebraMap K₀ L₀)).Splits)
    (hgsplit : (g.map (algebraMap K₀ L₀)).Splits)
    (hbound : ∀ x ∈ f.rootSet L₀, ∀ x' ∈ f.rootSet L₀, x ≠ x' →
      2 * (((f.natDegree + 1) * ε) ^ (f.natDegree : ℝ)⁻¹ * max ‖x‖ 1) +
        ((f.natDegree + 1) * ε) ^ (f.natDegree : ℝ)⁻¹ * max ‖x'‖ 1 <
          ‖x - x'‖) :
    g.Separable := by
  classical
  let radius (x : L₀) : ℝ :=
    ((f.natDegree + 1) * ε) ^ (f.natDegree : ℝ)⁻¹ * max ‖x‖ 1
  have hexists (x : f.rootSet L₀) :
      ∃ y : g.rootSet L₀, ‖x.1 - y.1‖ < radius x.1 := by
    obtain ⟨y, hy, hxy⟩ :=
      exists_aroots_norm_sub_lt_of_norm_coeff_sub_lt hε (mem_rootSet.mp x.2).2
        hfm hgm hdeg hcoeff hgsplit
    refine ⟨⟨y, ?_⟩, hxy⟩
    rw [mem_rootSet']
    exact mem_aroots'.mp hy
  choose φ hφ using hexists
  have hφinj : Function.Injective φ := by
    intro x x' heq
    apply Subtype.ext
    by_contra hxx'
    have hφeq : (φ x).1 = (φ x').1 := congrArg Subtype.val heq
    have htriangle :
        ‖x.1 - x'.1‖ ≤ ‖x.1 - (φ x).1‖ + ‖x'.1 - (φ x').1‖ := by
      calc
        ‖x.1 - x'.1‖ = ‖(x.1 - (φ x).1) + ((φ x).1 - x'.1)‖ := by
          rw [sub_add_sub_cancel]
        _ ≤ ‖x.1 - (φ x).1‖ + ‖(φ x).1 - x'.1‖ := norm_add_le _ _
        _ = ‖x.1 - (φ x).1‖ + ‖x'.1 - (φ x').1‖ := by
          rw [hφeq]
          congr 1
          exact norm_sub_rev _ _
    have hclose :
        ‖x.1 - (φ x).1‖ + ‖x'.1 - (φ x').1‖ <
          ‖x.1 - x'.1‖ := by
      apply (add_lt_add (hφ x) (hφ x')).trans
      have hb := hbound x.1 x.2 x'.1 x'.2 hxx'
      have hradius : 0 ≤ radius x.1 := by
        dsimp [radius]
        positivity
      linarith
    exact (not_lt_of_ge htriangle) hclose
  have hcard_le : Fintype.card (f.rootSet L₀) ≤ Fintype.card (g.rootSet L₀) :=
    Fintype.card_le_of_injective φ hφinj
  have hcard_f : Fintype.card (f.rootSet L₀) = f.natDegree :=
    card_rootSet_eq_natDegree hfsep hfsplit
  have hcard_g_le : Fintype.card (g.rootSet L₀) ≤ g.natDegree := by
    rw [Set.fintypeCard_eq_ncard]
    exact ncard_rootSet_le g L₀
  apply (card_rootSet_eq_natDegree_iff_of_splits hgm.ne_zero hgsplit).mp
  omega

/-- Quantitative root continuity supplies the rootwise Krasner hypothesis, and
hence one inclusion of root-generated fields, whenever its explicit bound is
smaller than every nontrivial conjugate distance of a reference root. This
does not assert that the comparison polynomial is separable or give the
reverse inclusion. -/
theorem adjoin_rootSet_le_adjoin_rootSet_of_norm_coeff_sub_lt
    {f g : K₀[X]} {ε : ℝ}
    (hε : 0 < ε)
    (hfm : f.Monic)
    (hgm : g.Monic)
    (hfsep : f.Separable)
    (hdeg : g.natDegree = f.natDegree)
    (hcoeff : ∀ i : ℕ, ‖g.coeff i - f.coeff i‖ < ε)
    (hfsplit : (f.map (algebraMap K₀ L₀)).Splits)
    (hgsplit : (g.map (algebraMap K₀ L₀)).Splits)
    (hbound : ∀ x ∈ f.rootSet L₀, ∀ x' : L₀,
      IsConjRoot K₀ x x' → x ≠ x' →
        ((f.natDegree + 1) * ε) ^ (f.natDegree : ℝ)⁻¹ * max ‖x‖ 1 <
          ‖x - x'‖) :
    IntermediateField.adjoin K₀ (f.rootSet L₀) ≤
      IntermediateField.adjoin K₀ (g.rootSet L₀) := by
  apply adjoin_rootSet_le_adjoin_rootSet_of_forall_exists_close hfsep hfsplit
  intro x hx
  obtain ⟨y, hy, hxy⟩ :=
    exists_aroots_norm_sub_lt_of_norm_coeff_sub_lt hε (mem_rootSet.mp hx).2
      hfm hgm hdeg hcoeff hgsplit
  refine ⟨y, ?_, fun x' hx' hne ↦ hxy.trans (hbound x hx x' hx' hne)⟩
  rw [mem_rootSet']
  exact mem_aroots'.mp hy

/-- If the coefficient radius separates the selected roots strongly enough,
the two root-generated fields are equal. The forward direction is the usual
Krasner argument. For the reverse direction, the selected-root map is a
bijection; every conjugate of a comparison root is matched with a distinct
reference root, and the asymmetric distance bound supplies the reverse
Krasner inequality. -/
theorem adjoin_rootSet_eq_of_norm_coeff_sub_lt
    {f g : K₀[X]} {ε : ℝ}
    (hε : 0 < ε)
    (hfm : f.Monic)
    (hgm : g.Monic)
    (hfsep : f.Separable)
    (hdeg : g.natDegree = f.natDegree)
    (hcoeff : ∀ i : ℕ, ‖g.coeff i - f.coeff i‖ < ε)
    (hfsplit : (f.map (algebraMap K₀ L₀)).Splits)
    (hgsplit : (g.map (algebraMap K₀ L₀)).Splits)
    (hbound : ∀ x ∈ f.rootSet L₀, ∀ x' ∈ f.rootSet L₀, x ≠ x' →
      2 * (((f.natDegree + 1) * ε) ^ (f.natDegree : ℝ)⁻¹ * max ‖x‖ 1) +
        ((f.natDegree + 1) * ε) ^ (f.natDegree : ℝ)⁻¹ * max ‖x'‖ 1 <
          ‖x - x'‖) :
    IntermediateField.adjoin K₀ (f.rootSet L₀) =
      IntermediateField.adjoin K₀ (g.rootSet L₀) := by
  classical
  let radius (x : L₀) : ℝ :=
    ((f.natDegree + 1) * ε) ^ (f.natDegree : ℝ)⁻¹ * max ‖x‖ 1
  have hexists (x : f.rootSet L₀) :
      ∃ y : g.rootSet L₀, ‖x.1 - y.1‖ < radius x.1 := by
    obtain ⟨y, hy, hxy⟩ :=
      exists_aroots_norm_sub_lt_of_norm_coeff_sub_lt hε (mem_rootSet.mp x.2).2
        hfm hgm hdeg hcoeff hgsplit
    refine ⟨⟨y, ?_⟩, hxy⟩
    rw [mem_rootSet']
    exact mem_aroots'.mp hy
  choose φ hφ using hexists
  have hgsep : g.Separable := separable_of_norm_coeff_sub_lt hε hfm hgm hfsep hdeg
    hcoeff hfsplit hgsplit hbound
  have hφinj : Function.Injective φ := by
    intro x x' heq
    apply Subtype.ext
    by_contra hxx'
    have hφeq : (φ x).1 = (φ x').1 := congrArg Subtype.val heq
    have htriangle :
        ‖x.1 - x'.1‖ ≤ ‖x.1 - (φ x).1‖ + ‖x'.1 - (φ x').1‖ := by
      calc
        ‖x.1 - x'.1‖ = ‖(x.1 - (φ x).1) + ((φ x).1 - x'.1)‖ := by
          rw [sub_add_sub_cancel]
        _ ≤ ‖x.1 - (φ x).1‖ + ‖(φ x).1 - x'.1‖ := norm_add_le _ _
        _ = ‖x.1 - (φ x).1‖ + ‖x'.1 - (φ x').1‖ := by
          rw [hφeq]
          congr 1
          exact norm_sub_rev _ _
    have hclose :
        ‖x.1 - (φ x).1‖ + ‖x'.1 - (φ x').1‖ <
          ‖x.1 - x'.1‖ := by
      apply (add_lt_add (hφ x) (hφ x')).trans
      have hb := hbound x.1 x.2 x'.1 x'.2 hxx'
      have hradius : 0 ≤ radius x.1 := by
        dsimp [radius]
        positivity
      linarith
    exact (not_lt_of_ge htriangle) hclose
  have hcard_f : Fintype.card (f.rootSet L₀) = f.natDegree :=
    card_rootSet_eq_natDegree hfsep hfsplit
  have hcard_g : Fintype.card (g.rootSet L₀) = g.natDegree :=
    card_rootSet_eq_natDegree hgsep hgsplit
  have hφsurj : Function.Surjective φ := by
    by_contra hnot
    have hlt := Fintype.card_lt_of_injective_not_surjective φ hφinj hnot
    omega
  apply le_antisymm
  · apply adjoin_rootSet_le_adjoin_rootSet_of_forall_exists_close hfsep hfsplit
    intro x hx
    refine ⟨(φ ⟨x, hx⟩).1, (φ ⟨x, hx⟩).2, ?_⟩
    intro x' hx' hne
    have hminpoly_dvd : minpoly K₀ x ∣ f := minpoly.dvd K₀ x (mem_rootSet.mp hx).2
    have hx'mem : x' ∈ f.rootSet L₀ := by
      apply mem_rootSet.mpr
      refine ⟨hfm.ne_zero, ?_⟩
      exact aeval_eq_zero_of_dvd_aeval_eq_zero hminpoly_dvd hx'.aeval_eq_zero
    apply (hφ ⟨x, hx⟩).trans
    have hb := hbound x hx x' hx'mem hne
    have hradius : 0 ≤ radius x' := by
      dsimp [radius]
      positivity
    have hradius_x : 0 ≤ radius x := by
      dsimp [radius]
      positivity
    dsimp [radius] at hb ⊢
    linarith
  · apply adjoin_le_adjoin_of_forall_exists_close
    intro y hy
    have hminpoly_dvd : minpoly K₀ y ∣ g := minpoly.dvd K₀ y (mem_rootSet.mp hy).2
    have hysep : IsSeparable K₀ y := hgsep.of_dvd hminpoly_dvd
    have hysplit : ((minpoly K₀ y).map (algebraMap K₀ L₀)).Splits :=
      hgsplit.of_dvd (map_ne_zero hgm.ne_zero)
        (Polynomial.map_dvd (algebraMap K₀ L₀) hminpoly_dvd)
    obtain ⟨x, hxy⟩ := hφsurj ⟨y, hy⟩
    refine ⟨hysep, hysplit, x.1, x.2,
      (isAlgebraic_of_mem_rootSet x.2).isIntegral, ?_⟩
    intro y' hy' hne
    have hy'mem : y' ∈ g.rootSet L₀ := by
      apply mem_rootSet.mpr
      refine ⟨hgm.ne_zero, ?_⟩
      exact aeval_eq_zero_of_dvd_aeval_eq_zero hminpoly_dvd hy'.aeval_eq_zero
    obtain ⟨x', hx'y'⟩ := hφsurj ⟨y', hy'mem⟩
    have hxx' : x.1 ≠ x'.1 := by
      intro heq
      have hsub : x = x' := Subtype.ext heq
      have himage : (⟨y, hy⟩ : g.rootSet L₀) = ⟨y', hy'mem⟩ := by
        calc
          (⟨y, hy⟩ : g.rootSet L₀) = φ x := hxy.symm
          _ = φ x' := congrArg φ hsub
          _ = ⟨y', hy'mem⟩ := hx'y'
      exact hne (congrArg Subtype.val himage)
    have hxclose : ‖x.1 - y‖ < radius x.1 := by
      simpa [hxy] using hφ x
    have hx'close : ‖x'.1 - y'‖ < radius x'.1 := by
      simpa [hx'y'] using hφ x'
    have htriangle :
        ‖x.1 - x'.1‖ ≤ ‖x.1 - y‖ + ‖y - y'‖ + ‖x'.1 - y'‖ := by
      calc
        ‖x.1 - x'.1‖ = ‖(x.1 - y) + (y - y') + (y' - x'.1)‖ := by
          congr 1
          ring
        _ ≤ ‖(x.1 - y) + (y - y')‖ + ‖y' - x'.1‖ := norm_add_le _ _
        _ ≤ (‖x.1 - y‖ + ‖y - y'‖) + ‖y' - x'.1‖ := by
          gcongr
          exact norm_add_le _ _
        _ = ‖x.1 - y‖ + ‖y - y'‖ + ‖x'.1 - y'‖ := by
          rw [norm_sub_rev y' x'.1]
    have hradius_lt : radius x.1 < ‖y - y'‖ := by
      by_contra hnot
      have hyy' : ‖y - y'‖ ≤ radius x.1 := le_of_not_gt hnot
      have hb := hbound x.1 x.2 x'.1 x'.2 hxx'
      have hsum :
          ‖x.1 - y‖ + ‖y - y'‖ + ‖x'.1 - y'‖ <
            2 * radius x.1 + radius x'.1 := by
        linarith
      have hb' : 2 * radius x.1 + radius x'.1 < ‖x.1 - x'.1‖ := by
        simpa [radius] using hb
      exact (not_lt_of_ge htriangle) (hsum.trans hb')
    simpa [norm_sub_rev y x.1] using hxclose.trans hradius_lt

/-- One-sided local stability of the field generated by the roots of a monic
separable polynomial. There is one positive coefficient radius such that every
monic same-degree comparison polynomial which is coefficientwise closer than
that radius and splits in the ambient field generates a field containing the
reference root field. No separability hypothesis is imposed on the comparison
polynomial, so this theorem deliberately gives only one inclusion. -/
theorem exists_pos_adjoin_rootSet_le_of_monic_separable
    {f : K₀[X]}
    (hfm : f.Monic)
    (hfsep : f.Separable)
    (hfsplit : (f.map (algebraMap K₀ L₀)).Splits) :
    ∃ ε : ℝ, 0 < ε ∧ ∀ {g : K₀[X]},
      g.Monic →
      g.natDegree = f.natDegree →
      (∀ i : ℕ, ‖g.coeff i - f.coeff i‖ < ε) →
      (g.map (algebraMap K₀ L₀)).Splits →
      IntermediateField.adjoin K₀ (f.rootSet L₀) ≤
        IntermediateField.adjoin K₀ (g.rootSet L₀) := by
  obtain ⟨ε, hε, hbound⟩ :=
    exists_pos_root_continuity_bound_lt_of_monic (L₀ := L₀) f hfm
  refine ⟨ε, hε, ?_⟩
  intro g hgm hdeg hcoeff hgsplit
  exact adjoin_rootSet_le_adjoin_rootSet_of_norm_coeff_sub_lt hε hfm hgm hfsep hdeg
    hcoeff hfsplit hgsplit hbound

/-- Local constancy of the root-generated field for monic separable
polynomials which split in one Krasner normed extension. The same uniform
coefficient radius also forces every comparison polynomial in the
neighbourhood to be separable. -/
theorem exists_pos_adjoin_rootSet_eq_of_monic_separable
    {f : K₀[X]}
    (hfm : f.Monic)
    (hfsep : f.Separable)
    (hfsplit : (f.map (algebraMap K₀ L₀)).Splits) :
    ∃ ε : ℝ, 0 < ε ∧ ∀ {g : K₀[X]},
      g.Monic →
      g.natDegree = f.natDegree →
      (∀ i : ℕ, ‖g.coeff i - f.coeff i‖ < ε) →
      (g.map (algebraMap K₀ L₀)).Splits →
      g.Separable ∧
        IntermediateField.adjoin K₀ (f.rootSet L₀) =
          IntermediateField.adjoin K₀ (g.rootSet L₀) := by
  obtain ⟨ε, hε, hbound⟩ :=
    exists_pos_two_add_root_continuity_bounds_lt_of_monic (L₀ := L₀) f hfm
  refine ⟨ε, hε, ?_⟩
  intro g hgm hdeg hcoeff hgsplit
  have hgsep := separable_of_norm_coeff_sub_lt hε hfm hgm hfsep hdeg hcoeff
    hfsplit hgsplit hbound
  exact ⟨hgsep, adjoin_rootSet_eq_of_norm_coeff_sub_lt hε hfm hgm hfsep hdeg
    hcoeff hfsplit hgsplit hbound⟩

end Quantitative

end IsKrasner
