/-
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Formal Frontier Agents
-/
module

public import PolynomialRootStability.Krasner
public import Mathlib.Analysis.Polynomial.Norm

/-!
# Normalized and ordinary coefficient stability

`IsKrasner.exists_pos_adjoin_rootSet_eq_of_separable_normalized` controls
the coefficients of `f * C f.leadingCoeff⁻¹` and
`g * C g.leadingCoeff⁻¹` directly; its comparison polynomial must be
nonzero. `Polynomial.exists_pos_norm_mul_leadingCoeff_inv_coeff_sub_lt`
turns an ordinary coefficientwise neighbourhood of an arbitrary nonzero
reference into a normalized one, proving the comparison nonzero.
`IsKrasner.exists_pos_adjoin_rootSet_eq_of_separable` combines them and
derives comparison separability and equality of root-generated intermediate
fields. The reference is separable and splits in a fixed `IsKrasner K L`
extension, as must the equal-`natDegree` comparison polynomial; nonzero
constants are included. No varying-degree neighbourhood or canonical
splitting-field object is asserted.
-/

public section

set_option warningAsError true

open Polynomial

noncomputable section

namespace IsKrasner

universe u v

variable {K : Type u} {L : Type v}
  [NormedField K] [NormedField L] [NormedAlgebra K L] [IsKrasner K L]

/-- Scale-invariant local constancy of the field generated by the roots of a
nonzero separable polynomial. Closeness is measured after dividing each
polynomial by its leading coefficient. -/
theorem exists_pos_adjoin_rootSet_eq_of_separable_normalized
    {f : K[X]}
    (hf0 : f ≠ 0)
    (hfsep : f.Separable)
    (hfsplit : (f.map (algebraMap K L)).Splits) :
    ∃ ε : ℝ, 0 < ε ∧ ∀ {g : K[X]},
      g ≠ 0 →
      g.natDegree = f.natDegree →
      (∀ i : ℕ,
        ‖(g * C g.leadingCoeff⁻¹).coeff i -
          (f * C f.leadingCoeff⁻¹).coeff i‖ < ε) →
      (g.map (algebraMap K L)).Splits →
      g.Separable ∧
        IntermediateField.adjoin K (f.rootSet L) =
          IntermediateField.adjoin K (g.rootSet L) := by
  classical
  have hfinv : f.leadingCoeff⁻¹ ≠ 0 :=
    inv_ne_zero (leadingCoeff_ne_zero.mpr hf0)
  have hfnmonic : (f * C f.leadingCoeff⁻¹).Monic :=
    monic_mul_leadingCoeff_inv hf0
  have hfnsep : (f * C f.leadingCoeff⁻¹).Separable :=
    hfsep.mul_unit (isUnit_C.mpr (IsUnit.mk0 _ hfinv))
  have hfnsplit :
      ((f * C f.leadingCoeff⁻¹).map (algebraMap K L)).Splits := by
    simpa [Polynomial.map_mul] using
      hfsplit.mul (Polynomial.Splits.C (algebraMap K L f.leadingCoeff⁻¹))
  obtain ⟨ε, hε, hstable⟩ :=
    exists_pos_adjoin_rootSet_eq_of_monic_separable hfnmonic hfnsep hfnsplit
  refine ⟨ε, hε, ?_⟩
  intro g hg0 hdeg hcoeff hgsplit
  have hginv : g.leadingCoeff⁻¹ ≠ 0 :=
    inv_ne_zero (leadingCoeff_ne_zero.mpr hg0)
  have hgnmonic : (g * C g.leadingCoeff⁻¹).Monic :=
    monic_mul_leadingCoeff_inv hg0
  have hgnsplit :
      ((g * C g.leadingCoeff⁻¹).map (algebraMap K L)).Splits := by
    simpa [Polynomial.map_mul] using
      hgsplit.mul (Polynomial.Splits.C (algebraMap K L g.leadingCoeff⁻¹))
  have hndeg :
      (g * C g.leadingCoeff⁻¹).natDegree =
        (f * C f.leadingCoeff⁻¹).natDegree := by
    simpa [natDegree_mul_leadingCoeff_inv g hg0,
      natDegree_mul_leadingCoeff_inv f hf0] using hdeg
  obtain ⟨hgnsep, hroot⟩ := hstable hgnmonic hndeg hcoeff hgnsplit
  have hgsep : g.Separable := hgnsep.of_mul_left
  have hfroots : (f * C f.leadingCoeff⁻¹).rootSet L = f.rootSet L := by
    rw [mul_comm, rootSet, aroots_C_mul _ hfinv, rootSet]
  have hgroots : (g * C g.leadingCoeff⁻¹).rootSet L = g.rootSet L := by
    rw [mul_comm, rootSet, aroots_C_mul _ hginv, rootSet]
  exact ⟨hgsep, by simpa [hfroots, hgroots] using hroot⟩

end IsKrasner

namespace Polynomial

variable {K : Type u} [NormedField K]

/-- Coefficientwise closeness to a nonzero polynomial forces coefficientwise
closeness of the corresponding monic normalizations, provided the comparison
polynomial has the same degree. -/
theorem exists_pos_norm_mul_leadingCoeff_inv_coeff_sub_lt
    {f : K[X]} (hf0 : f ≠ 0) {η : ℝ} (hη : 0 < η) :
    ∃ ε : ℝ, 0 < ε ∧ ∀ {g : K[X]},
      g.natDegree = f.natDegree →
      (∀ i : ℕ, ‖g.coeff i - f.coeff i‖ < ε) →
      g ≠ 0 ∧ ∀ i : ℕ,
        ‖(g * C g.leadingCoeff⁻¹).coeff i -
          (f * C f.leadingCoeff⁻¹).coeff i‖ < η := by
  have hflead : f.leadingCoeff ≠ 0 := leadingCoeff_ne_zero.mpr hf0
  have hA : 0 < ‖f.leadingCoeff⁻¹‖ + 1 := by positivity
  have hB : 0 < f.supNorm + 1 := by
    have := f.supNorm_nonneg
    linarith
  have ht : 0 < min 1 (η / (2 * (f.supNorm + 1))) := by
    rw [lt_min_iff]
    exact ⟨by norm_num, div_pos hη (mul_pos (by norm_num) hB)⟩
  obtain ⟨δ, hδ, hinv⟩ :=
    (Metric.continuousAt_iff.mp (continuousAt_inv₀ hflead)) _ ht
  let ε := min (‖f.leadingCoeff‖ / 2)
    (min δ (η / (2 * (‖f.leadingCoeff⁻¹‖ + 1))))
  have hε : 0 < ε := by
    dsimp [ε]
    rw [lt_min_iff, lt_min_iff]
    exact ⟨div_pos (norm_pos_iff.mpr hflead) (by norm_num), hδ,
      div_pos hη (mul_pos (by norm_num) hA)⟩
  refine ⟨ε, hε, ?_⟩
  intro g hdeg hcoeff
  have hlc : ‖g.leadingCoeff - f.leadingCoeff‖ < ε := by
    calc
      ‖g.leadingCoeff - f.leadingCoeff‖ =
          ‖g.coeff g.natDegree - f.coeff f.natDegree‖ := by simp
      _ = ‖g.coeff f.natDegree - f.coeff f.natDegree‖ := by rw [hdeg]
      _ < ε := hcoeff f.natDegree
  have hεlead : ε ≤ ‖f.leadingCoeff‖ / 2 := min_le_left _ _
  have hg0 : g ≠ 0 := by
    intro hg
    have hgcoeff : g.coeff f.natDegree = 0 := by simp [hg]
    have hsmall := hcoeff f.natDegree
    rw [hgcoeff, coeff_natDegree, zero_sub, norm_neg] at hsmall
    have hfnorm : 0 < ‖f.leadingCoeff‖ := norm_pos_iff.mpr hflead
    linarith
  have hεδ : ε ≤ δ :=
    (min_le_right _ _).trans (min_le_left _ _)
  have hεη : ε ≤ η / (2 * (‖f.leadingCoeff⁻¹‖ + 1)) :=
    (min_le_right _ _).trans (min_le_right _ _)
  have hinvclose :
      ‖g.leadingCoeff⁻¹ - f.leadingCoeff⁻¹‖ <
        min 1 (η / (2 * (f.supNorm + 1))) := by
    have := hinv (show dist g.leadingCoeff f.leadingCoeff < δ by
      simpa [dist_eq_norm] using hlc.trans_le hεδ)
    simpa [dist_eq_norm] using this
  have hinvone : ‖g.leadingCoeff⁻¹ - f.leadingCoeff⁻¹‖ < 1 :=
    (lt_min_iff.mp hinvclose).1
  have hinvη :
      ‖g.leadingCoeff⁻¹ - f.leadingCoeff⁻¹‖ <
        η / (2 * (f.supNorm + 1)) :=
    (lt_min_iff.mp hinvclose).2
  have hginvbound : ‖g.leadingCoeff⁻¹‖ < ‖f.leadingCoeff⁻¹‖ + 1 := by
    calc
      ‖g.leadingCoeff⁻¹‖ =
          ‖(g.leadingCoeff⁻¹ - f.leadingCoeff⁻¹) + f.leadingCoeff⁻¹‖ := by ring_nf
      _ ≤ ‖g.leadingCoeff⁻¹ - f.leadingCoeff⁻¹‖ +
          ‖f.leadingCoeff⁻¹‖ := norm_add_le _ _
      _ < 1 + ‖f.leadingCoeff⁻¹‖ := by
        simpa [add_comm] using add_lt_add_right hinvone ‖f.leadingCoeff⁻¹‖
      _ = ‖f.leadingCoeff⁻¹‖ + 1 := by ring
  refine ⟨hg0, ?_⟩
  intro i
  rw [coeff_mul_C, coeff_mul_C]
  have hid :
      g.coeff i * g.leadingCoeff⁻¹ - f.coeff i * f.leadingCoeff⁻¹ =
        (g.coeff i - f.coeff i) * g.leadingCoeff⁻¹ +
          f.coeff i * (g.leadingCoeff⁻¹ - f.leadingCoeff⁻¹) := by ring
  rw [hid]
  calc
    ‖(g.coeff i - f.coeff i) * g.leadingCoeff⁻¹ +
        f.coeff i * (g.leadingCoeff⁻¹ - f.leadingCoeff⁻¹)‖
        ≤ ‖(g.coeff i - f.coeff i) * g.leadingCoeff⁻¹‖ +
          ‖f.coeff i * (g.leadingCoeff⁻¹ - f.leadingCoeff⁻¹)‖ :=
            norm_add_le _ _
    _ = ‖g.coeff i - f.coeff i‖ * ‖g.leadingCoeff⁻¹‖ +
          ‖f.coeff i‖ * ‖g.leadingCoeff⁻¹ - f.leadingCoeff⁻¹‖ := by
            rw [norm_mul, norm_mul]
    _ < ε * (‖f.leadingCoeff⁻¹‖ + 1) +
          (f.supNorm + 1) * (η / (2 * (f.supNorm + 1))) := by
            apply add_lt_add
            · exact mul_lt_mul_of_nonneg_of_pos (hcoeff i) (le_of_lt hginvbound)
                (norm_nonneg _) hA
            · exact mul_lt_mul_of_nonneg_of_pos
                ((f.le_supNorm i).trans_lt (by linarith [f.supNorm_nonneg]))
                (le_of_lt hinvη) (norm_nonneg _)
                (div_pos hη (mul_pos (by norm_num) hB))
    _ ≤ (η / (2 * (‖f.leadingCoeff⁻¹‖ + 1))) *
          (‖f.leadingCoeff⁻¹‖ + 1) +
          (f.supNorm + 1) * (η / (2 * (f.supNorm + 1))) := by
            gcongr
    _ = η := by field_simp; ring

end Polynomial

namespace IsKrasner

variable {K : Type u} {L : Type v}
  [NormedField K] [NormedField L] [NormedAlgebra K L] [IsKrasner K L]

/-- Local constancy of the field generated by the roots of an arbitrary
nonzero separable polynomial. Unlike the monic theorem, closeness is measured
on the original coefficients; the radius also keeps the comparison leading
coefficient nonzero. -/
theorem exists_pos_adjoin_rootSet_eq_of_separable
    {f : K[X]}
    (hf0 : f ≠ 0)
    (hfsep : f.Separable)
    (hfsplit : (f.map (algebraMap K L)).Splits) :
    ∃ ε : ℝ, 0 < ε ∧ ∀ {g : K[X]},
      g.natDegree = f.natDegree →
      (∀ i : ℕ, ‖g.coeff i - f.coeff i‖ < ε) →
      (g.map (algebraMap K L)).Splits →
      g.Separable ∧
        IntermediateField.adjoin K (f.rootSet L) =
          IntermediateField.adjoin K (g.rootSet L) := by
  obtain ⟨η, hη, hnormalized⟩ :=
    exists_pos_adjoin_rootSet_eq_of_separable_normalized hf0 hfsep hfsplit
  obtain ⟨ε, hε, hcoeff⟩ :=
    Polynomial.exists_pos_norm_mul_leadingCoeff_inv_coeff_sub_lt hf0 hη
  refine ⟨ε, hε, ?_⟩
  intro g hdeg hclose hgsplit
  obtain ⟨hg0, hnormalizedClose⟩ := hcoeff hdeg hclose
  exact hnormalized hg0 hdeg hnormalizedClose hgsplit

end IsKrasner
